name: Deploy Dist
on: [push, workflow_dispatch]

jobs:
  deploy-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Dist
        run: |
          echo "Cloning Repository..."
          echo "Bye Bye"
          echo "${{ toJson(github) }}"
          git clone https://github.com/${{ github.repository }}.git

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test